[package]
name = "spcm-gui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
env_logger = "0.11.3"
iced = "0.12.1"
log = "0.4.22"
regex = "1.10.5"
spcm = { version = "0.1.0", path = "../spcm" }
