[package]
name = "mirrormount-joystick"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.82"
sdl2 = { version = "0.36.0", path = "../rust-sdl2/", features = ["no_more_string_error"] }
